spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false

logging:
  level:
    root: ${LOG_LEVEL:INFO}

app:
  seed:
    enabled: true
    admin-password: ${APP_SEED_ADMIN_PASSWORD:admin123}
    user-password: ${APP_SEED_USER_PASSWORD:password}
